"""initial schema

Revision ID: b26729c3ee69
Revises: 
Create Date: 2026-06-23 09:52:12.748204
"""
from alembic import op
import sqlalchemy as sa


revision = 'b26729c3ee69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_file_ids', sa.JSON(), nullable=False),
    sa.Column('requested_folder_ids', sa.JSON(), nullable=False),
    sa.Column('zip_key', sa.String(length=1024), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_owner_parent', ['owner_id', 'parent_folder_id'], unique=False)

    op.create_table('folders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index('ix_folders_owner_parent', ['owner_id', 'parent_folder_id'], unique=False)

    op.create_table('public_links',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('shares',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('principal_type', sa.String(length=16), nullable=False),
    sa.Column('principal_value', sa.String(length=320), nullable=False),
    sa.Column('principal_display', sa.String(length=320), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('shared_by', sa.String(length=64), nullable=False),
    sa.Column('shared_by_email', sa.String(length=320), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'principal_type', 'principal_value', name='uq_share_principal')
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index('ix_shares_principal', ['principal_type', 'principal_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index('ix_shares_principal')

    op.drop_table('shares')
    op.drop_table('public_links')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index('ix_folders_owner_parent')

    op.drop_table('folders')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_owner_parent')

    op.drop_table('files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('idempotency_records')
    op.drop_table('archive_jobs')
    # ### end Alembic commands ###
